[project]
name = "sign-text-to-pose"
description = "Model for generating pose files from text"
version = "0.0.1"
authors = [
    { name = "Amit Moryossef", email = "amitmoryossef@gmail.com" }
]
readme = "README.md"

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint"
]

[tool.setuptools]
packages = ["text_to_pose"]