name: Pose-to-Segments


on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'text_to_pose/**'
      - 'text_to_text/**'
      - 'pose_to_text/**'
      - 'video_to_pose/**'
      - 'pose_to_video/**'


jobs:
  test:
    name: pose-to-segments
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Requirements
        run: pip install .[dev]

      - name: Lint Code
        run: pylint pose_to_segments

      - name: Run tests
        run: pytest pose_to_segments
