name: Pose-to-Text


on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'text_to_pose/**'
      - 'text_to_text/**'
      - 'pose_to_text/**'
      - 'video_to_pose/**'


jobs:
  test:
    name: pose-to-text
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Requirements
        run: |
          pip install .[dev]

      - name: Lint Code
        run: pylint pose_to_text

      - name: Run tests
        run: pytest pose_to_text
